/**
 * The payment methods offered in the picker. Ids are Adyen txvariants, which is
 * what the vendored logo files are keyed by.
 *
 * Generated by scripts/fetch-payment-logos.mjs — do not edit by hand.
 */

export const METHOD_GROUPS = [
  { id: 'cards', label: 'Cards' },
  { id: 'wallets', label: 'Wallets' },
  { id: 'banking', label: 'Bank transfer and debit' },
  { id: 'bnpl', label: 'Buy now, pay later' },
  { id: 'local', label: 'Local favourites' },
] as const;

export type MethodGroupId = (typeof METHOD_GROUPS)[number]['id'];

export interface PaymentMethodSpec {
  readonly id: string;
  readonly label: string;
  readonly group: MethodGroupId;
}

export const PAYMENT_METHODS: readonly PaymentMethodSpec[] = [
  { id: 'visa', label: 'Visa', group: 'cards' },
  { id: 'mc', label: 'Mastercard', group: 'cards' },
  { id: 'amex', label: 'American Express', group: 'cards' },
  { id: 'maestro', label: 'Maestro', group: 'cards' },
  { id: 'discover', label: 'Discover', group: 'cards' },
  { id: 'jcb', label: 'JCB', group: 'cards' },
  { id: 'cup', label: 'UnionPay', group: 'cards' },
  { id: 'girocard', label: 'girocard', group: 'cards' },
  { id: 'bcmc', label: 'Bancontact', group: 'cards' },
  { id: 'applepay', label: 'Apple Pay', group: 'wallets' },
  { id: 'googlepay', label: 'Google Pay', group: 'wallets' },
  { id: 'paypal', label: 'PayPal', group: 'wallets' },
  { id: 'cashapp', label: 'Cash App Pay', group: 'wallets' },
  { id: 'alipay', label: 'Alipay', group: 'wallets' },
  { id: 'wechatpay', label: 'WeChat Pay', group: 'wallets' },
  { id: 'ideal', label: 'iDEAL', group: 'banking' },
  { id: 'directEbanking', label: 'Klarna Pay Now', group: 'banking' },
  { id: 'eps', label: 'EPS', group: 'banking' },
  { id: 'trustly', label: 'Trustly', group: 'banking' },
  { id: 'blik', label: 'BLIK', group: 'banking' },
  { id: 'pix', label: 'Pix', group: 'banking' },
  { id: 'sepadirectdebit', label: 'SEPA Direct Debit', group: 'banking' },
  { id: 'klarna', label: 'Klarna', group: 'bnpl' },
  { id: 'afterpaytouch', label: 'Afterpay', group: 'bnpl' },
  { id: 'affirm', label: 'Affirm', group: 'bnpl' },
  { id: 'twint', label: 'TWINT', group: 'local' },
  { id: 'swish', label: 'Swish', group: 'local' },
  { id: 'mobilepay', label: 'MobilePay', group: 'local' },
  { id: 'vipps', label: 'Vipps', group: 'local' },
  { id: 'mbway', label: 'MB WAY', group: 'local' },
];

const BY_ID = new Map(PAYMENT_METHODS.map((method) => [method.id, method] as const));

export function paymentMethodSpec(id: string): PaymentMethodSpec | null {
  return BY_ID.get(id) ?? null;
}

export function isPaymentMethodId(value: unknown): value is string {
  return typeof value === 'string' && BY_ID.has(value);
}

export function methodLabel(id: string): string {
  return BY_ID.get(id)?.label ?? id;
}
